[package]
name = "test-suite"
version = "0.1.0"
edition = "2021"

[dependencies]
eure-tree = { workspace = true }
eure-parol = { workspace = true }
eure-value = { workspace = true }
eure-json = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
