[package]
name = "eure-lint"
version.workspace = true
edition.workspace = true
description = "Linter for Eure files"
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["eure", "lint", "linter", "static-analysis"]

[dependencies]
