[package]
name = "serde-eure"
version.workspace = true
edition.workspace = true
description = "Serde support for Eure format"
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["deserialization", "eure", "serde", "serialization"]

[dependencies]
ahash = { workspace = true }
eure = { workspace = true }
eure-json = { workspace = true }
eure-parol = { workspace = true }
eure-tree = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
