[package]
name = "eure"
version = "0.1.0"
edition = "2024"
description = "EURE core library"
readme = "README.md"
homepage = "https://eure.dev"
repository = "https://github.com/Hihaheho/eure"
license = "MIT OR Apache-2.0"
keywords = ["configuration", "data-format", "eure", "serialization"]

[dependencies]
eros = { workspace = true }
eure-parol = { workspace = true }
eure-tree = { workspace = true }
eure-value = { workspace = true }
thiserror = { workspace = true }
